# Copyright 2026 sina.pahlavan@canonical.com
# See LICENSE file for licensing details.

[tox]
no_package = True
skip_missing_interpreters = True
envlist = lint, static, unit
min_version = 4.0.0

[vars]
src_path = {tox_root}/src
tst_path = {tox_root}/tests
all_path = {[vars]src_path} {[vars]tst_path}
uv_flags = --frozen --isolated

[testenv]
allowlist_externals = uv
set_env =
    PYTHONPATH = {tox_root}/lib:{[vars]src_path}
    PYTHONBREAKPOINT=pdb.set_trace
    PY_COLORS=1
pass_env =
    PYTHONPATH
    CHARM_PATH

[testenv:format]
description = Apply coding style standards to code
commands =
    uv run {[vars]uv_flags} --group lint ruff format {[vars]all_path}
    uv run {[vars]uv_flags} --group lint ruff check --fix {[vars]all_path}

[testenv:lint]
description = Lint the code
commands =
    uv run {[vars]uv_flags} --group lint codespell {tox_root}
    uv run {[vars]uv_flags} --group lint ruff check {[vars]all_path}
    uv run {[vars]uv_flags} --group lint ruff format --check --diff {[vars]all_path}

[testenv:static]
description = Run static checks
commands =
    uv run {[vars]uv_flags} --group lint --group unit --group integration pyright {[vars]all_path}

[testenv:unit]
description = Run unit tests
commands =
    uv run {[vars]uv_flags} --group unit coverage run --source={[vars]src_path} -m pytest \
        {[vars]tst_path}/unit {posargs}
    uv run {[vars]uv_flags} --group unit coverage report

[testenv:integration]
description = Run integration tests
commands =
    uv run {[vars]uv_flags} --group integration pytest --exitfirst \
        {[vars]tst_path}/integration {posargs}
